### ISSUE TITLE
Readme example fails

### ISSUE THREAD

**Issue by toonn** [manuels/bulletinboard-dht#6]
After building v0.5.3 and running the example in the readme this is the result I get:

```bash
method return time=1526921765.224010 sender=:1.30 -> destination=:1.32 serial=4 reply_serial=2
   array [
   ]
```

I assume the array shouldn't be empty but I'm not sure why it is.

**Comment by manuels** [comment]
The thing is that the bootstrap nodes are down and it was a bit much to keep the infrastructure up 24/7 for one person.
If you want a stable DHT, I would recommend opendht.

**Comment by toonn** [comment]
Reason I was trying out bulletinboard is wireguard-p2p. How hard/easy would it be to have wireguard-p2p work with opendht?

**Comment by manuels** [comment]
Not really, I am planing a complete rewrite of wireguard-p2p using rust's new async approach and opendht, but async is not really working reliably in rust, yet.

**Comment by toonn** [comment]
Do you have some design/motivation docs? I wonder why you need async but then again I don't really know what wg-p2p does so no wonder I wonder. This would be useful enough for me right now that I might put some effort into a rewrite.

I'm closing the issue, not to stop discussion but because the original issue was resolved in the first comment.
